source('R/sample_kmeans.R')
library(terra)
f <- system.file('ex/elev.tif', package = 'terra')
r <- terra::rast(f)
myweights <- r / unlist(terra::global(r, 'max', na.rm = TRUE)); myweights <- myweights^2
out1 <- sample_kmeans(input = r, clusters = 4, ncells = 1000, weights = myweights, use_xy = TRUE, seed = 224)
out2 <- sample_kmeans(input = r, clusters = 4, ncells = 1000, weights = myweights, use_xy = TRUE, seed = 224)
cat('points identical:', identical(out1$points, out2$points), '\n')
print(out1$points)
print(out2$points)
